### ISSUE TITLE
Entryä lisättäessä validointi ei aina toimi

### ISSUE THREAD

**Issue by iivorait** [EvilHenchmen/ohtu-miniprojekti#1]
Jos Cite-kentän täyttää ja Author-kentän jättää tyhjäksi, tulee Whitelabel Error Page eikä ihmisluettava virheviesti

**Comment by Uskon** [comment]
Muistaakseni ainakin Article- ja Book-tyyppisten viitteiden lisääminen ei ole vielä validoitavissa, kun Inproceedings taisi olla korkeimmalla prioriteetillä.

**Comment by iivorait** [comment]
Kyllä tuo näyttää validoivan kaikkia kolmea, mutta virhettä ei käsitellä em. tapauksessa oikein.
Tässä konsolin ekat rivit:
java.lang.NullPointerException: null
	at wad.domain.EntryValidator.test(EntryValidator.java:28)
	at wad.service.EntryService.saveEntry(EntryService.java:51)
	at wad.controller.EntryController.add(EntryController.java:61) 

Nyt on ilmassa "prosessihajua": kirjoitin testin tälle, joka ei mene läpi, enkä korjannut koodia...

**Comment by paddyman45** [comment]
Lisäsin pari riviä koodia validaattoriin, Entry-luokan fields-muuttuja oli null ja validaattori käytti sitä tarkistamatta
